version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - ls -la dist/

artifacts:
  base-directory: dist
  files:
    - '**/*'

cache:
  paths:
    - node_modules/**/*
